database:
  image: mysql
  container_name: database.dev
  command: mysqld --user=root --verbose
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: "anthologieAPI"
    MYSQL_USER: "anthologieAPI"
    MYSQL_PASSWORD: "3xEWiLeFI6WznAes"
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_ALLOW_EMPTY_PASSWORD: "no"
